name    'jlondon-zookeeper'
version '0.1.0'
source 'UNKNOWN'
author 'Justice London'
license 'Apache License, Version 2.0'
summary 'Puppet zookeeper cluster module'
description 'Module which allows you to simply install/configure an entire zookeeper cluster'
project_page 'http://github.com/justicel/puppet-zookeeper'
dependency 'ripienaar/concat', '>= 0.2.0'
